import { Link } from "wouter";
import { ExternalLink, AlertTriangle, ArrowRight } from "lucide-react";

interface Decision {
  id: string;
  title: string;
  body: string;
}

const DECISIONS: Decision[] = [
  {
    id: "D1",
    title: "Plugin first, upstream second",
    body: "Start as an external Mermaid diagram plugin registered via registerDiagram(). This reduces core-maintainer review burden, allows faster syntax iteration, and lets the community validate the approach before it lands in core.",
  },
  {
    id: "D2",
    title: "bpmn-beta, not bpmn",
    body: "Use bpmn-beta as the DSL header keyword until the grammar, rendering model, and user expectations stabilize. The -beta suffix is a promise to users that the syntax may change.",
  },
  {
    id: "D3",
    title: "Descriptive subset only",
    body: "Do not attempt executable BPMN, XML interchange, or full BPMN 2.0 standard conformance in v1. A readable descriptive subset covering common process documentation patterns delivers more value than an exhaustive implementation.",
  },
  {
    id: "D4",
    title: "Readability over exhaustiveness",
    body: "A developer with no BPMN background should be able to read a bpmn-beta diagram. The DSL is optimized for the 80% of use cases, not the full BPMN 2.0 specification.",
  },
  {
    id: "D5",
    title: "Shape fidelity matters",
    body: "BPMN users will reject incorrect notation. The renderer must get core shapes right: event borders, task rectangles, gateway markers, sequence flow arrowheads, and default flow slashes. Wrong shapes erode credibility immediately.",
  },
  {
    id: "D6",
    title: "No bpmn-js runtime dependency",
    body: "bpmn-js is a comprehensive BPMN toolkit with different design goals. Using it as a v1 dependency would couple this project to a heavyweight dependency and a different rendering philosophy. The prototype renderer is built from scratch.",
  },
  {
    id: "D7",
    title: "AI-generation readiness as a first-class goal",
    body: "The DSL is explicitly designed to be generated by LLMs without syntax repair. Short IDs, predictable keywords, and low-boilerplate structure reduce generation failure rates. This is valuable in agentic documentation workflows and positions the project at the intersection of process modeling and AI-generated structured output.",
  },
  {
    id: "D8",
    title: "Intermediate BPMN database separates parsing from rendering",
    body: "BpmnDb is the canonical representation between parser and renderer. This separation means a future Langium parser can populate the same data model, a future renderer can consume it, and future validations run against the same normalized structure. Without this separation, the system would be a string-to-SVG hack with no extensibility path.",
  },
];

interface Risk {
  label: string;
  severity: "High" | "Medium" | "Low";
  mitigation: string;
}

const RISKS: Risk[] = [
  { label: "Scope creep into full BPMN 2.0", severity: "High", mitigation: "Publish explicit v1 support matrix. Say no early and often." },
  { label: "DSL fragmentation with existing prototypes", severity: "High", mitigation: "Engage on GitHub issue #7699 before locking syntax. Don't ship in isolation." },
  { label: "Poor layout quality", severity: "High", mitigation: "Start with constrained left-to-right layout. Complexity grows with scope." },
  { label: "Incorrect BPMN notation", severity: "High", mitigation: "Validate shape library against BPMN reference examples. Get a BPMN practitioner to review." },
  { label: "Maintainer reluctance", severity: "Medium", mitigation: "Plugin-first path. Tests, examples, and docs reduce the review surface." },
  { label: "User expectation of XML export", severity: "Medium", mitigation: "Mark XML interchange as a future milestone in every public communication." },
  { label: "Mermaid theming conflicts", severity: "Medium", mitigation: "Use existing Mermaid theme variables. Do not introduce new theme properties in v1." },
  { label: "Overengineering the grammar", severity: "Medium", mitigation: "Hand-written parser is fine for the prototype. Langium migration when the grammar is proven." },
];

const SEVERITY_COLORS: Record<string, string> = {
  High: "text-destructive bg-destructive/10 border-destructive/30",
  Medium: "text-yellow-700 dark:text-yellow-400 bg-yellow-50 dark:bg-yellow-900/20 border-yellow-200 dark:border-yellow-800",
  Low: "text-muted-foreground bg-muted border-muted-border",
};

const CONTRIBUTE_LINKS = [
  { label: "GitHub issue #7699 — Native BPMN 2.0 support", url: "https://github.com/mermaid-js/mermaid/issues/7699" },
  { label: "GitHub issue #2623 — BPMN support discussion", url: "https://github.com/mermaid-js/mermaid/issues/2623" },
  { label: "GitHub issue #660 — Older BPMN diagram request", url: "https://github.com/mermaid-js/mermaid/issues/660" },
  { label: "Mermaid — registerDiagram() API docs", url: "https://mermaid.js.org/config/theming.html" },
  { label: "OMG BPMN 2.0 specification", url: "https://www.omg.org/spec/BPMN/" },
  { label: "bpmn.org", url: "https://www.bpmn.org/" },
];

export default function About() {
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 py-12">
      <div className="mb-10">
        <h1 className="text-2xl font-bold text-foreground" data-testid="heading-about">
          About & Contribution
        </h1>
        <p className="mt-2 text-sm text-muted-foreground max-w-2xl leading-relaxed">
          Key decisions made during the design of <code className="font-mono text-xs bg-muted px-1 py-0.5 rounded">bpmn-beta</code>,
          the risks this project is managing, and how to get involved.
        </p>
        <div className="flex items-center gap-3 mt-4 flex-wrap" data-testid="about-badges">
          <a
            href="https://github.com/OKHP3/mermaid-diagram-bpmn/actions/workflows/deploy-gh-pages.yml"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="Deploy to GitHub Pages workflow status"
          >
            <img
              src="https://github.com/OKHP3/mermaid-diagram-bpmn/actions/workflows/deploy-gh-pages.yml/badge.svg"
              alt="Deploy to GitHub Pages"
              height="20"
            />
          </a>
          <img
            src="https://img.shields.io/badge/BP--SKILL-15%20skills-5b6ee1?style=flat&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNiAxNiI+PHBhdGggZmlsbD0id2hpdGUiIGQ9Ik04IDFhNyA3IDAgMSAwIDAgMTRBNyA3IDAgMCAwIDggMXptMCAyYTUgNSAwIDEgMSAwIDEwQTUgNSAwIDAgMSA4IDN6bS0uNSAydjQuNWwzLjUgMi0uNS44LTQtMi4zVjV6Ii8+PC9zdmc+"
            alt="BP-SKILL: 15 skills"
            height="20"
          />
        </div>
      </div>

      {/* Decisions */}
      <section className="mb-14">
        <h2 className="text-base font-semibold text-foreground mb-6" data-testid="heading-decisions">
          Key product decisions
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {DECISIONS.map(d => (
            <div key={d.id} className="p-5 rounded-lg border border-border bg-card" data-testid={`card-decision-${d.id}`}>
              <div className="flex items-start gap-3">
                <span className="font-mono text-xs text-primary font-bold mt-0.5 shrink-0">{d.id}</span>
                <div>
                  <p className="text-sm font-semibold text-foreground mb-1.5">{d.title}</p>
                  <p className="text-xs text-muted-foreground leading-relaxed">{d.body}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Risks */}
      <section className="mb-14">
        <h2 className="text-base font-semibold text-foreground mb-4" data-testid="heading-risks">
          Risk register
        </h2>
        <div className="rounded-lg border border-border overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="border-b border-border bg-muted/50">
                  <th className="text-left px-4 py-3 font-semibold text-muted-foreground uppercase tracking-wide">Risk</th>
                  <th className="text-left px-4 py-3 font-semibold text-muted-foreground uppercase tracking-wide w-24">Severity</th>
                  <th className="text-left px-4 py-3 font-semibold text-muted-foreground uppercase tracking-wide">Mitigation</th>
                </tr>
              </thead>
              <tbody>
                {RISKS.map((r, i) => (
                  <tr key={i} className={`border-b border-border last:border-0 ${i % 2 === 0 ? "bg-card" : "bg-muted/10"}`} data-testid={`row-risk-${i}`}>
                    <td className="px-4 py-3 text-foreground align-top leading-relaxed">{r.label}</td>
                    <td className="px-4 py-3 align-top">
                      <span className={`inline-flex items-center px-2 py-0.5 rounded-full border text-xs font-medium ${SEVERITY_COLORS[r.severity]}`}>
                        {r.severity}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-muted-foreground align-top leading-relaxed">{r.mitigation}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* Project heritage */}
      <section className="mb-14">
        <h2 className="text-base font-semibold text-foreground mb-4" data-testid="heading-heritage">
          Project heritage and stack positioning
        </h2>
        <div className="rounded-lg border border-border bg-card p-5 mb-5">
          <p className="text-xs text-muted-foreground leading-relaxed mb-4">
            BPMN for Mermaid is the <strong className="text-foreground">process-structure and notation layer</strong> of
            the OKHP³ Visual Language Stack — a set of complementary tools that take a raw process idea all
            the way to a styled, documented, published artifact.
          </p>
          <div className="font-mono text-xs leading-relaxed text-muted-foreground bg-muted/40 rounded px-4 py-3 border border-border">
            <div>ReFolDec <span className="text-foreground/40">— recursive fold/unfold transformation theory</span></div>
            <div className="pl-4">└─ <span className="text-primary font-semibold">BPMN for Mermaid</span> <span className="text-foreground/40">— process-structure and notation layer</span></div>
            <div className="pl-10">└─ Mermaid Theme Builder <span className="text-foreground/40">— visual governance and renderer profiles</span></div>
            <div className="mt-1">skillz / BP-SKILL <span className="text-foreground/40">— executable agent workflows for the process lifecycle</span></div>
            <div>OverKill Hill <span className="text-foreground/40">— public narrative and routing surface</span></div>
          </div>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-5">
          <div className="p-4 rounded-lg border border-border bg-card">
            <p className="text-xs font-semibold text-foreground mb-2">Process lifecycle (steps 1–8)</p>
            <ol className="text-xs text-muted-foreground leading-relaxed space-y-1 list-none">
              {[
                "Raw process idea",
                "Guided capture — skillz elicitation",
                "Process narrative — PNS.md",
                "Structured model — BpmnDb",
                "bpmn-beta syntax",
                "Mermaid diagram — SVG output",
                "Visual governance — Mermaid Theme Builder",
                "Publication — skillz packaging",
              ].map((step, i) => (
                <li key={i} className="flex gap-2">
                  <span className={`font-mono font-bold shrink-0 ${i >= 3 && i <= 5 ? "text-primary" : "text-muted-foreground/50"}`}>{i + 1}.</span>
                  <span className={i >= 3 && i <= 5 ? "text-foreground" : ""}>{step}</span>
                </li>
              ))}
            </ol>
            <p className="text-xs text-muted-foreground/60 mt-3 border-t border-border pt-2">
              This project owns steps 4–6. Steps 1–3 are BP-SKILL. Steps 7–8 are Mermaid Theme Builder and BP-SKILL respectively.
            </p>
          </div>
          <div className="p-4 rounded-lg border border-border bg-card">
            <p className="text-xs font-semibold text-foreground mb-3">Lineage</p>
            <p className="text-xs text-muted-foreground leading-relaxed mb-3">
              Earlier experiments under the names <strong className="text-foreground">PathScrib-R</strong>,
              Path Scribbler, and <strong className="text-foreground">Flowpilot Scribbler</strong> explored
              conversational process discovery and Mermaid diagram generation as declarative-agent-like
              instruction sets.
            </p>
            <p className="text-xs text-muted-foreground leading-relaxed">
              BPMN for Mermaid formalizes that lineage into a structured process-notation layer. The ancestor
              projects' public story lives on OverKill Hill — not in this codebase.
            </p>
          </div>
        </div>
      </section>

      {/* Competitive landscape */}
      <section className="mb-14">
        <h2 className="text-base font-semibold text-foreground mb-4" data-testid="heading-competitive">
          Competitive landscape
        </h2>
        <p className="text-xs text-muted-foreground mb-4 max-w-2xl leading-relaxed">
          bpmn-beta should not compete head-on with full BPM suites. It should own a specific lane:{" "}
          <strong className="text-foreground">BPMN descriptive diagrams for Markdown-first, Git-native, AI-assisted documentation workflows.</strong>
        </p>
        <div className="rounded-lg border border-border overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="border-b border-border bg-muted/50">
                  <th className="text-left px-4 py-3 font-semibold text-muted-foreground uppercase tracking-wide">Tool</th>
                  <th className="text-left px-4 py-3 font-semibold text-muted-foreground uppercase tracking-wide">Strength</th>
                  <th className="text-left px-4 py-3 font-semibold text-muted-foreground uppercase tracking-wide">Weakness relative to bpmn-beta</th>
                </tr>
              </thead>
              <tbody>
                {[
                  { tool: "Mermaid flowchart", strength: "Already available, simple", weakness: "Not semantically BPMN" },
                  { tool: "PlantUML", strength: "Mature text diagrams, broad support", weakness: "Not Mermaid-native" },
                  { tool: "bpmn.io / bpmn-js", strength: "Strong BPMN ecosystem", weakness: "XML/modeler-centric, heavier runtime" },
                  { tool: "Camunda Modeler", strength: "Professional BPMN tooling", weakness: "Enterprise/modeler oriented, not Markdown-first" },
                  { tool: "Visio", strength: "Familiar enterprise diagramming", weakness: "Binary/visual workflow, weak Git-native story" },
                  { tool: "Signavio", strength: "Enterprise process platform", weakness: "Heavyweight, commercial, not developer-doc native" },
                  { tool: "Mermaid Chart", strength: "Strong Mermaid ecosystem", weakness: "BPMN still appears as an opportunity gap" },
                ].map((row, i) => (
                  <tr key={row.tool} className={`border-b border-border last:border-0 ${i % 2 === 0 ? "bg-card" : "bg-muted/10"}`}>
                    <td className="px-4 py-3 font-semibold text-foreground align-top">{row.tool}</td>
                    <td className="px-4 py-3 text-muted-foreground align-top leading-relaxed">{row.strength}</td>
                    <td className="px-4 py-3 text-foreground align-top leading-relaxed">{row.weakness}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* Known limitations */}
      <section className="mb-14">
        <h2 className="text-base font-semibold text-foreground mb-4" data-testid="heading-limitations">
          Known limitations
        </h2>
        <p className="text-xs text-muted-foreground mb-4 max-w-2xl leading-relaxed">
          This project is promising but not finished. Honest scope is part of the contribution posture.
        </p>
        <div className="flex flex-col gap-3">
          {[
            { label: "Not an official Mermaid diagram type", intentional: false, note: "Does not yet render natively inside Mermaid consumers. The target external plugin architecture is documented but the artifact is still a React prototype." },
            { label: "Parser is hand-written", intentional: false, note: "Good for iteration; insufficient for upstream-quality grammar maturity. Strategy: hand-written prototype first, Langium for plugin v1." },
            { label: "Pool/lane/message-flow support is experimental", intentional: false, note: "Cross-lane flow routing is approximate. Pool widths may not align. Verify output before relying on it." },
            { label: "No BPMN XML import/export", intentional: true, note: "Intentional for v1. User writes lightweight DSL, not BPMN XML. XML is deliberately decoupled from diagram authoring." },
            { label: "No execution semantics", intentional: true, note: "Intentional. The target is descriptive diagramming, not workflow execution. This is also not in scope for a Mermaid diagram type." },
            { label: "No formal conformance certification", intentional: true, note: "The project avoids claiming full BPMN 2.0 conformance. It targets the Descriptive Conformance sub-class only." },
            { label: "Layout engine is prototype-grade", intentional: false, note: "Usable for prototype validation but will need improvement for production adoption. Constraint-based layout with dagre/ELK integration is planned." },
          ].map((item, i) => (
            <div key={i} className="flex items-start gap-3 p-4 rounded-lg border border-border bg-card">
              <AlertTriangle size={13} className={`shrink-0 mt-0.5 ${item.intentional ? "text-primary/50" : "text-amber-600 dark:text-amber-400"}`} />
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-xs font-semibold text-foreground">{item.label}</span>
                  {item.intentional && (
                    <span className="text-xs px-1.5 py-0.5 rounded bg-primary/10 text-primary/70 border border-primary/20 font-mono">intentional</span>
                  )}
                </div>
                <p className="text-xs text-muted-foreground leading-relaxed">{item.note}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* How to contribute */}
      <section className="mb-14">
        <h2 className="text-base font-semibold text-foreground mb-4" data-testid="heading-how-to-contribute">
          How to get involved
        </h2>
        <div className="flex flex-col gap-3 max-w-2xl mb-6">
          <div className="forge-card" data-testid="card-bp-skill-suite">
            <p className="text-sm font-semibold text-foreground mb-1">BP-SKILL v0.2 Suite</p>
            <p className="text-xs text-muted-foreground leading-relaxed">
              A companion suite of 15 agent skills covering the full bpmn-beta authoring lifecycle —
              from process discovery through publication. Designed for LLM-assisted documentation
              workflows that generate valid <code className="font-mono bg-muted px-1 py-0.5 rounded">bpmn-beta</code> diagrams.
            </p>
          </div>
          <div className="forge-card flex items-start justify-between gap-4">
            <div>
              <p className="text-sm font-semibold text-foreground mb-1">New to the project?</p>
              <p className="text-xs text-muted-foreground leading-relaxed">
                The BP-SKILL Suite Walkthrough shows how all 15 skills connect — from intake to publication —
                in a single bpmn-beta pipeline diagram and step-by-step handoff table.
              </p>
            </div>
            <Link href="/walkthrough" className="forge-btn-primary shrink-0 inline-flex items-center gap-2 text-xs">
              Suite Walkthrough <ArrowRight size={12} />
            </Link>
          </div>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {[
            {
              step: "1",
              title: "Comment on existing issues",
              body: "Start at GitHub issue #7699. Signal interest, share your use case, and see what prior work exists. Do not create a duplicate issue.",
            },
            {
              step: "2",
              title: "Try the playground",
              body: "Use the Playground page to write bpmn-beta diagrams. File an issue in this repo if the parser mishandles valid syntax.",
            },
            {
              step: "3",
              title: "Contribute to the spec",
              body: "Open a discussion about element syntax, edge cases, or deferred features you'd like to prioritize. The DSL is not locked.",
            },
          ].map(s => (
            <div key={s.step} className="p-5 rounded-lg border border-border bg-card">
              <div className="w-8 h-8 rounded-full bg-accent border border-accent-border flex items-center justify-center text-accent-foreground text-xs font-bold font-mono mb-3">
                {s.step}
              </div>
              <p className="text-sm font-semibold text-foreground mb-1.5">{s.title}</p>
              <p className="text-xs text-muted-foreground leading-relaxed">{s.body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Reference links */}
      <section>
        <h2 className="text-base font-semibold text-foreground mb-4" data-testid="heading-links">
          Reference links
        </h2>
        <div className="flex flex-col gap-2">
          {CONTRIBUTE_LINKS.map(link => (
            <a
              key={link.url}
              href={link.url}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-3 px-4 py-3 rounded-lg border border-border bg-card hover:border-primary/50 hover:bg-accent/30 transition-colors group"
              data-testid={`link-ref-${link.label.slice(0, 20).toLowerCase().replace(/\s+/g, '-')}`}
            >
              <span className="text-xs text-foreground flex-1">{link.label}</span>
              <ExternalLink size={12} className="text-muted-foreground/60 group-hover:text-muted-foreground transition-colors shrink-0" />
            </a>
          ))}
        </div>
      </section>
    </div>
  );
}
