/**
 * playwright.config.ts
 *
 * Playwright configuration for the real-browser E2E suite.
 *
 * Covers browser spec files:
 *   - e2e/host-demo.spec.ts     — mermaid.registerExternalDiagrams() integration (Task #209)
 *   - e2e/playground-error-highlight.spec.ts — Playground source diagnostics and compressed URL fallback
 *   - e2e/url-sharing.spec.ts   — canonical and custom Playground shared URLs
 *   - e2e/visual-regression.spec.ts — mobile layout and visual snapshot checks (Task #213)
 *
 * Prerequisites: the app must be built before this suite runs.
 *   pnpm --filter @workspace/mermaid-diagram-bpmn run build
 *   pnpm --filter @workspace/mermaid-diagram-bpmn run test:e2e
 *
 * The webServer block starts `vite preview` (serving the built dist) and
 * waits for it to be healthy before launching tests.
 *
 * VISUAL SNAPSHOTS
 * ─────────────────
 * Baseline PNGs are stored in app/e2e/__snapshots__/ using the template
 *   {snapshotDir}/{arg}-{platform}{ext}
 * where {platform} is the OS name (linux / darwin / win32).  Baseline images
 * committed to the repo are Linux/Chromium, generated by CI. Visual snapshot
 * scripts explicitly select the Chromium project; host-demo E2E runs on all
 * configured browser engines.
 *
 * Update baselines:
 *   pnpm --filter @workspace/mermaid-diagram-bpmn run test:e2e:update-snapshots
 */

import { defineConfig, devices } from '@playwright/test';

const PREVIEW_PORT = 4174; // avoid clashing with dev server on 3000

export default defineConfig({
  testDir: './e2e',
  fullyParallel: false, // single-worker to avoid Mermaid registration races
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  workers: 1,
  reporter: process.env.CI ? [['github'], ['json', { outputFile: 'e2e-results.json' }]] : 'list',
  timeout: 60_000,

  // Visual snapshot configuration
  // Baselines live in app/e2e/__snapshots__/ with the OS name as a suffix so
  // snapshots generated on different platforms don't overwrite each other.
  snapshotDir: './e2e/__snapshots__',
  snapshotPathTemplate: '{snapshotDir}/{arg}-{platform}{ext}',

  use: {
    baseURL: `http://localhost:${PREVIEW_PORT}`,
    headless: true,
    actionTimeout: 30_000,
    screenshot: 'only-on-failure',
    trace: 'retain-on-failure',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],

  webServer: {
    // Serves the production build from app/dist/public/.
    // Build must run before test:e2e (handled by CI job ordering).
    command: `PORT=${PREVIEW_PORT} pnpm --filter @workspace/mermaid-diagram-bpmn run serve`,
    url: `http://localhost:${PREVIEW_PORT}`,
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
    stdout: 'ignore',
    stderr: 'pipe',
  },
});
