// AUTO-GENERATED by scripts/extract-pns-transitions.mjs — do not edit manually.
// Source: app/src/data/skills-registry.ts
//   consumes fields  — PNS.md [status] pattern → before
//   produces fields  — PNS.md [status] pattern → after  (backfilled from PNS_LIFECYCLE)
// Re-run:  node scripts/extract-pns-transitions.mjs

export interface PnsTransition {
  before: string | null;
  after:  string | null;
}

export const PNS_TRANSITIONS: Record<string, PnsTransition> = {
  "okhp3-process-intake-and-scope"      : { before: null              , after: "draft-intake" },
  "okhp3-stakeholder-and-role-mapping"  : { before: "draft-intake"    , after: "scoped" },
  "okhp3-elicitation-interviews"        : { before: "scoped"          , after: "elicited" },
  "okhp3-as-is-process-capture"         : { before: "elicited"        , after: "documented-as-is" },
  "okhp3-process-narrative-authoring"   : { before: "documented-as-is", after: "modeled" },
  "okhp3-visual-process-modeling"       : { before: "modeled"         , after: null },
  "okhp3-process-gap-exception-analysis": { before: "modeled"         , after: "analyzed" },
  "okhp3-future-state-change-strategy"  : { before: "analyzed"        , after: null },
  "okhp3-decision-model-authoring"      : { before: "modeled"         , after: null },
  "okhp3-process-validation-scoring"    : { before: "modeled"         , after: "validated" },
  "okhp3-process-measures-controls"     : { before: "validated"       , after: null },
  "okhp3-sop-work-instructions"         : { before: "validated"       , after: null },
  "okhp3-raci-governance-matrix"        : { before: "modeled"         , after: null },
  "okhp3-sipoc-generation"              : { before: "modeled"         , after: null },
  "okhp3-publication-handoff-packaging" : { before: "validated"       , after: "packaged" },
};
