// AUTO-GENERATED by scripts/extract-pns-transitions.mjs — do not edit manually.
// Source: artifacts/mermaid-diagram-bpmn/src/data/skills-registry.ts
//   consumes fields  — PNS.md [status] pattern → before
//   produces fields  — PNS.md [status] pattern → after  (backfilled from PNS_LIFECYCLE)
// Re-run:  node scripts/extract-pns-transitions.mjs

export interface PnsTransition {
  before: string | null;
  after:  string | null;
}

export const PNS_TRANSITIONS: Record<string, PnsTransition> = {
  "process-intake-and-scope"                : { before: null              , after: "draft-intake" },
  "stakeholder-and-role-mapping"            : { before: "draft-intake"    , after: "scoped" },
  "elicitation-and-interview-facilitation"  : { before: "scoped"          , after: "elicited" },
  "as-is-process-capture"                   : { before: "elicited"        , after: "documented-as-is" },
  "process-narrative-authoring"             : { before: "documented-as-is", after: "modeled" },
  "visual-process-modeling"                 : { before: "modeled"         , after: null },
  "process-gap-and-exception-analysis"      : { before: "modeled"         , after: "analyzed" },
  "future-state-and-change-strategy"        : { before: "analyzed"        , after: null },
  "decision-model-authoring"                : { before: "modeled"         , after: null },
  "process-validation-and-quality-scoring"  : { before: "modeled"         , after: "validated" },
  "process-measures-and-controls-definition": { before: "validated"       , after: null },
  "sop-and-work-instruction-generation"     : { before: "validated"       , after: null },
  "raci-and-governance-matrix-generation"   : { before: null              , after: null },
  "sipoc-generation"                        : { before: null              , after: null },
  "publication-and-handoff-packaging"       : { before: "validated"       , after: "packaged" },
};
