// AUTO-GENERATED by scripts/extract-skill-deps.mjs — do not edit manually.
// Source: skills/*/SKILL.md frontmatter (depends_on field).
// Re-run:  node scripts/extract-skill-deps.mjs

export const SKILL_DEPS: Record<string, readonly string[]> = {
  "okhp3-process-intake-and-scope": [],
  "okhp3-stakeholder-and-role-mapping": ["okhp3-process-intake-and-scope"],
  "okhp3-elicitation-interviews": ["okhp3-process-intake-and-scope"],
  "okhp3-as-is-process-capture": ["okhp3-process-intake-and-scope"],
  "okhp3-process-narrative-authoring": ["okhp3-process-intake-and-scope","okhp3-stakeholder-and-role-mapping"],
  "okhp3-visual-process-modeling": ["okhp3-process-narrative-authoring"],
  "okhp3-process-gap-exception-analysis": ["okhp3-as-is-process-capture"],
  "okhp3-future-state-change-strategy": ["okhp3-process-gap-exception-analysis"],
  "okhp3-decision-model-authoring": ["okhp3-process-narrative-authoring"],
  "okhp3-process-validation-scoring": ["okhp3-process-narrative-authoring"],
  "okhp3-process-measures-controls": ["okhp3-process-narrative-authoring"],
  "okhp3-sop-work-instructions": ["okhp3-process-narrative-authoring"],
  "okhp3-raci-governance-matrix": ["okhp3-process-narrative-authoring"],
  "okhp3-sipoc-generation": ["okhp3-process-narrative-authoring"],
  "okhp3-publication-handoff-packaging": ["okhp3-process-narrative-authoring","okhp3-visual-process-modeling","okhp3-sop-work-instructions"],
};
