// AUTO-GENERATED by scripts/extract-skill-deps.mjs — do not edit manually.
// Source: skills/*/SKILL.md frontmatter (depends_on field).
// Re-run:  node scripts/extract-skill-deps.mjs

export const SKILL_DEPS: Record<string, readonly string[]> = {
  "process-intake-and-scope": [],
  "stakeholder-and-role-mapping": ["process-intake-and-scope"],
  "elicitation-and-interview-facilitation": ["process-intake-and-scope"],
  "as-is-process-capture": ["process-intake-and-scope"],
  "process-narrative-authoring": ["process-intake-and-scope","stakeholder-and-role-mapping"],
  "visual-process-modeling": ["process-narrative-authoring"],
  "process-gap-and-exception-analysis": ["as-is-process-capture"],
  "future-state-and-change-strategy": ["process-gap-and-exception-analysis"],
  "decision-model-authoring": ["process-narrative-authoring"],
  "process-validation-and-quality-scoring": ["process-narrative-authoring"],
  "process-measures-and-controls-definition": ["process-narrative-authoring"],
  "sop-and-work-instruction-generation": ["process-narrative-authoring"],
  "raci-and-governance-matrix-generation": ["process-narrative-authoring"],
  "sipoc-generation": ["process-narrative-authoring"],
  "publication-and-handoff-packaging": ["process-narrative-authoring","visual-process-modeling","sop-and-work-instruction-generation"],
};
